name: Sarah E Broome Photography
favicon: null
layout_spectrum: 0.52731
typography_spectrum: 0.13491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5ddce'
    - '#b1c7bb'
    - '#6f9daa'
    - '#88afb4'
    - '#4d7b8b'
  brandStrength: 0.875
  lightness: 0.7776248699519783
  saturation: 0.7143834831658751
  rhythmicContrast: 0.31815454736351967
purpose: []
