name: Sarah E Broome Photography
favicon: null
layout_spectrum: 0.20604384457692504
typography_spectrum: 0.9004371382761747
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9249961338937283
  lightness: 0.7776248699519783
  saturation: 0.7143834831658751
  rhythmicContrast: 0.31815454736351967
purpose: []
