name: Sarah E Broome Photography
favicon: null
layout_spectrum: 0.74311
typography_spectrum: 0.13491
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#272624'
    - '#9a8975'
    - '#73695d'
    - '#504b45'
    - '#bda991'
  brandStrength: 0.9249961338937283
  lightness: 0.7776248699519783
  saturation: 0.7143834831658751
  rhythmicContrast: 0.31815454736351967
purpose: []
